<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>10.0</LangVersion>
		<Platforms>x64</Platforms>
		<PlatformTarget>x64</PlatformTarget>
		<SignAssembly>True</SignAssembly>
		<AssemblyOriginatorKeyFile>Ring.Schema.Tests.snk</AssemblyOriginatorKeyFile>
		<NoWarn>RCS1196</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Bogus" />
		<PackageReference Include="coverlet.collector">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.DotNet.ILCompiler" />
		<PackageReference Include="Microsoft.NET.ILLink.Tasks" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="xunit.v3" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Ring.Schema\Ring.Schema.csproj" />
	</ItemGroup>


</Project>
