<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<PublishSingleFile>true</PublishSingleFile>
		<TargetFrameworks>net9.0;net8.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>10.0</LangVersion>
		<AnalysisLevel>6.0-all</AnalysisLevel>
		<AssemblyVersion>1.0.0.225</AssemblyVersion>
		<FileVersion>1.0.0.225</FileVersion>
		<RepositoryType>https://github.com/sganhy/RingCsharp.git</RepositoryType>
		<RepositoryUrl>https://github.com/sganhy/RingCsharp</RepositoryUrl>
		<Description>SchemaMgr - Ring Zero</Description>
		<Title>SchemaMgr</Title>
		<Version>1.0.0-beta</Version>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<NoWarn>CA1307;CA1802;S3267;IDE0066</NoWarn>
		<PublishTrimmed>True</PublishTrimmed>
		<PublishAot>True</PublishAot>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<SignAssembly>True</SignAssembly>
		<Copyright>Copyright © 2025</Copyright>
		<NuGetAuditLevel>critical</NuGetAuditLevel>
		<Product>SchemaMgr - Ring Zero</Product>
		<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
		<PlatformTarget>x64</PlatformTarget>
		<Platforms>x64</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.DotNet.ILCompiler" />
		<PackageReference Include="Microsoft.NET.ILLink.Tasks" />
		<PackageReference Include="CommandLineParser" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Providers\Ring.InfluxDB\Ring.InfluxDB.csproj" />
	  <ProjectReference Include="..\..\Providers\Ring.MySql\Ring.MySql.csproj" />
	  <ProjectReference Include="..\..\Providers\Ring.Oracle\Ring.Oracle.csproj" />
	  <ProjectReference Include="..\..\Providers\Ring.PostgreSQL\Ring.PostgreSQL.csproj" />
	  <ProjectReference Include="..\..\Providers\Ring.Sqlite\Ring.Sqlite.csproj" />
	  <ProjectReference Include="..\..\Providers\Ring.SqlServer\Ring.SqlServer.csproj" />
	  <ProjectReference Include="..\..\Ring.Data\Ring.Data.csproj" />
	  <ProjectReference Include="..\..\Ring.Schema\Ring.Schema.csproj" />
	</ItemGroup>

</Project>
